### ISSUE TITLE
Cannot configure parsec

### ISSUE THREAD

**Issue by chroniceel93** [kajmaj87/parsec-intel#1]
Bit of an issue, because the build-in noise cancellation does not play well on my computer.

**Comment by kajmaj87** [comment]
Could you explain the issue in more detail?

**Comment by chroniceel93** [comment]
Sorry, I don't even remember writing this! Basically, I could not turn off echo cancellation on parsec! I eventually figured out that I could kill it by modifying the dockerfile. It looks like in the intervening time you have come up with your own fix and passed a user directory on to hold config files, so this whole problem is bunk! Again, sorry for being so vague!
